title: My Hacker Theme
description: A hacker-inspired Jekyll theme with Matrix-style animations.
baseurl: "/documentation" # Leave blank for hosting on GitHub Pages
url: "https://ryanm.dev"
markdown: kramdown
theme: hacker
